name: Publish Release

on:
  workflow_dispatch:
    inputs:
      koraVersion:
        description: 'Kora release version number'
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - id: kora_changelog
        run: |
          KORA_CHANGELOG_TAG=${{ github.event.inputs.koraVersion }}
          KORA_CHANGELOG_TAG=${KORA_CHANGELOG_TAG//.}
          echo "KORA_CHANGELOG_TAG=${KORA_CHANGELOG_TAG}" >> $GITHUB_OUTPUT

      - name: Notify new release to Telegram
        uses: appleboy/telegram-action@master
        env:
          KORA_VERSION: ${{ github.event.inputs.koraVersion }}
          KORA_CHANGELOG_TAG: ${{ steps.kora_changelog.outputs.KORA_CHANGELOG_TAG }}
        with:
          to: ${{ secrets.TELEGRAM_RELEASE_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Вышла новая версия Kora: ${{ env.KORA_VERSION }}
            
            Больше подробностей [тут](https://kora-projects.github.io/kora-docs/ru/changelog/changelog/#${{ env.KORA_CHANGELOG_TAG }})
