name: Publish Release

on:
  release:
    branches: [ "master" ]
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Retrieve the secret and decode it to a file
        env:
          GPG_KEY: ${{ secrets.SONATYPE_GPG_KEY }}
        run: echo "$GPG_KEY" | base64 --decode > /tmp/secring.gpg

      - name: Retrieve the gradle.properties
        env:
          SIGN_OSSRH_GRADLE_PROPERTIES: ${{ secrets.SONATYPE_GRADLE_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle
          echo "$SIGN_OSSRH_GRADLE_PROPERTIES" | base64 --decode > ~/.gradle/gradle.properties

      - name: Print release version
        run: echo "Release version - $KORA_VERSION"
        env:
          KORA_VERSION: ${{ github.event.release.tag_name }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assemble jar

      - name: Execute Gradle Publish to OSS
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.secretKeyRingFile=/tmp/secring.gpg
        env:
          REPO_USER: ${{ secrets.SONATYPE_USERNAME }}
          REPO_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          KORA_VERSION: ${{ github.event.release.tag_name }}
